[build-system]
requires = ["maturin==1.4"]
build-backend = "maturin"

[project]
name = "$name"
version = "0.2.5"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Rust",
]
dynamic = ["description"]

[tool.maturin]
features = ["pyo3/extension-module"]
profile = "release"
