[package]
name = "mistralrs"
readme = "README.md"
authors = ["Eric Buehler"]
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
mistralrs-core = { version = "0.3.0", path = "../mistralrs-core" }
anyhow.workspace = true
tokio.workspace = true
candle-core.workspace = true
serde_json.workspace = true
serde.workspace = true
image.workspace = true
indexmap.workspace = true
either.workspace = true
futures.workspace = true
reqwest.workspace = true
rand = "0.8.5"

[features]
cuda = ["mistralrs-core/cuda"]
cudnn = ["mistralrs-core/cudnn"]
metal = ["mistralrs-core/metal"]
flash-attn = ["cuda", "mistralrs-core/flash-attn"]
accelerate = ["mistralrs-core/accelerate"]
mkl = ["mistralrs-core/mkl"]

[[example]]
name = "simple"
required-features = []

[[example]]
name = "grammar"
required-features = []

[[example]]
name = "quantized"
required-features = []

[[example]]
name = "isq"
required-features = []

[[example]]
name = "lora"
required-features = []

[[example]]
name = "xlora"
required-features = []

[[example]]
name = "lora_activation"
required-features = []

[[example]]
name = "gguf_locally"
required-features = []

[[example]]
name = "phi3v"
required-features = []

[[example]]
name = "idefics2"
required-features = []

[[example]]
name = "llava"
required-features = []

[[example]]
name = "llava_next"
required-features = []

[[example]]
name = "anymoe"
required-features = []

[[example]]
name = "anymoe_lora"
required-features = []

[[example]]
name = "paged_attn"
required-features = []

[[example]]
name = "tools"
required-features = []

[[example]]
name = "batching"
required-features = []

[[example]]
name = "topology"
required-features = []

[[example]]
name = "phi3_5_moe"
required-features = []
